# Generated by Django 4.2.13 on 2024-06-17 12:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Admin_Login_App', '0003_alter_courses_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Careers',
            new_name='Career',
        ),
        migrations.RenameModel(
            old_name='courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='partners_logo',
            new_name='PartnerLogo',
        ),
        migrations.RenameModel(
            old_name='PlacementStories',
            new_name='PlacementStory',
        ),
        migrations.RenameModel(
            old_name='technologies',
            new_name='Technology',
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='ph_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
